# This is a basic workflow to help you get started with Actions

name: Project Automation - Card Adder

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [labeled, unlabeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Access the payload
        run: |
          LABEL_NAME="${{github.event.label.name}}"
          ACTION="${{github.event.action}}"
          ISSUE_TITLE="${{github.event.issue.title}}"
          ISSUE_URL="${{github.event.issue.url}}"
          ISSUE_NUMBER="${{github.event.issue.number}}"
          
          PROJECT_BOARD_ID=5484631
          PROJECT_TODO_COL_ID=10860613
          PROJECT_IN_PROGRESS_COL_ID=10860614
          PROJECT_DONE_COL_ID=10860615
          PROJECT_BOARD_URL="https://github.com/d12/GitHub-Actions-Testing/projects/1"
          
          MAGIC_LABEL_NAME="test"
          
          if [[ $LABEL_NAME = $MAGIC_LABEL_NAME ]]
          then
            if [[ $ACTION = "labeled" ]]
            then
              echo "Test label was added to $ISSUE_TITLE"
            else
              echo "Test label was removed from $ISSUE_TITLE"
              echo "Not interesting. Skipping"
              exit 0
            fi
          else
            echo "Not an interesting event. Skipping"
            exit 0
          fi
          
          echo "Adding note to project board..."
          curl \
          --url https://api.github.com/projects/columns/$PROJECT_TODO_COL_ID/cards \
          -X POST \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
           --header 'accept: application/vnd.github.inertia-preview+json' \
          -d "{\"note\":\"(**From Borg**) [$ISSUE_TITLE]($ISSUE_URL)\nUnassigned\"}" > add_card_payload
           
          CARD_ID=$(cat add_card_payload | jq .id)
          CARD_URL=$(cat add_card_payload | jq .id)
           
          echo "Adding comment to issue..."
          curl \
          --url https://api.github.com/repos/d12/GitHub-Actions-Testing/issues/${ISSUE_NUMBER}/comments \
          -X POST \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -d "{\"body\":\"Beep boop. Because this was labeled with $MAGIC_LABEL_NAME, I've added it to [the shared project board]($CARD_URL).\n\n<sub>Card ID: $CARD_ID\"}" > /dev/null
          
