name: Project Automation - Issue Labeled

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [unlabeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"

      - name: Setup Ruby env
        run: |
          cd .github/scripts

          RUBYOPT="-W0" gem install bundler
          RUBYOPT="-W0" bundle update --bundler
          RUBYOPT="-W0" bundle install

      - name: Run the issue_labeled Ruby script
        run: |
          cd .github/scripts

          RUBYOPT="-W0" bundle exec ruby issue_labeled.rb \
            --label_name "${{github.event.label.name}}" \
            --issue_number "${{github.event.issue.number}}" \
            --github_token "${{ secrets.GITHUB_TOKEN }}"
